[package]
name = "rust-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
magic-crypt = "3.1.12"
rand = "0.8.5"
rocket = "0.5.0-rc.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
